{
 "title": "Watchtower",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Scans",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "watchtower_scans_total" }
   ]
  },
  {
   "title": "Skipped Scans",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "watchtower_scans_skipped" }
   ]
  },
  {
   "title": "Container Updates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "watchtower_containers_scanned" },
    { "expr": "watchtower_containers_failed" },
    { "expr": "watchtower_containers_updated" }
   ]
  },
  {
   "title": "Failed Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "watchtower_containers_failed" }
   ]
  },
  {
   "title": "Updated Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "watchtower_containers_updated" }
   ]
  }
 ]
}